In [85]:
import os
os.getcwd()

'/Users/ayagad'

In [86]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier 
from sklearn.pipeline import Pipeline 
from sklearn.metrics  import classification_report

In [87]:
df = pd.read_csv("/Users/ayagad/Downloads/creditcard.csv")

In [88]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [89]:
df.shape

(284807, 31)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [91]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [92]:
df.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [93]:
duplicate_values = df[df.duplicated()]
print(duplicate_values)

            Time        V1        V2        V3        V4        V5        V6  \
33          26.0 -0.529912  0.873892  1.347247  0.145457  0.414209  0.100223
35          26.0 -0.535388  0.865268  1.351076  0.147575  0.433680  0.086983
113         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283
114         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283
115         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283
...          ...       ...       ...       ...       ...       ...       ...
282987  171288.0  1.912550 -0.455240 -1.750654  0.454324  2.089130  4.160019
283483  171627.0 -1.464380  1.368119  0.815992 -0.601282 -0.689115 -0.487154
283485  171627.0 -1.457978  1.378203  0.811515 -0.603760 -0.711883 -0.471672
284191  172233.0 -2.667936  3.160505 -3.355984  1.007845 -0.377397 -0.109730
284193  172233.0 -2.691642  3.123168 -3.339407  1.017018 -0.293095 -0.167054

              V7        V8        V9  ...       V21       V22       V23  \
33      0.711206  0.176066 -0.286717  ...  0.046949  0.208105 -0.185548
35      0.693039  0.179742 -0.285642  ...  0.049526  0.206537 -0.187108
113    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092
114    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092
115    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092
...          ...       ...       ...  ...       ...       ...       ...
282987 -0.881302  1.081750  1.022928  ... -0.524067 -1.337510  0.473943
283483 -0.303778  0.884953  0.054065  ...  0.287217  0.947825 -0.218773
283485 -0.282535  0.880654  0.052808  ...  0.284205  0.949659 -0.216949
284191 -0.667233  2.309700 -1.639306  ...  0.391483  0.266536 -0.079853
284193 -0.745886  2.325616 -1.634651  ...  0.402639  0.259746 -0.086606

             V24       V25       V26       V27       V28  Amount  Class
33      0.001031  0.098816 -0.552904 -0.073288  0.023307    6.14      0
35      0.000753  0.098117 -0.553471 -0.078306  0.025427    1.77      0
113    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0
114    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0
115    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0
...          ...       ...       ...       ...       ...     ...    ...
282987  0.616683 -0.283548 -1.084843  0.073133 -0.036020   11.99      0
283483  0.082926  0.044127  0.639270  0.213565  0.119251    6.82      0
283485  0.083250  0.044944  0.639933  0.219432  0.116772   11.93      0
284191 -0.096395  0.086719 -0.451128 -1.183743 -0.222200   55.66      0
284193 -0.097597  0.083693 -0.453584 -1.205466 -0.213020   36.74      0

[1081 rows x 31 columns]

In [94]:
df.drop_duplicates(inplace=True)

In [95]:
duplicate_values = df[df.duplicated()]
print(duplicate_values)

Empty DataFrame
Columns: [Time, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20, V21, V22, V23, V24, V25, V26, V27, V28, Amount, Class]
Index: []

[0 rows x 31 columns]

In [96]:
fraud_coun=df["Class"].value_counts()

In [97]:
fraud_rate=100*fraud_coun/df.shape[0]

In [98]:
fraud_data = pd.concat([fraud_coun,fraud_rate],axis=1).reset_index()
fraud_data.columns=['class','count','per']
fraud_data

   class   count       per
0      0  283253  99.83329
1      1     473   0.16671

In [99]:
df_fraud= df[df['Class']==1]
df_not_fraud= df[df['Class']==0]
df_not_fraud_sampled=df_not_fraud.sample(df_fraud.shape[0],replace=False,random_state=101)
df_balance= pd.concat([df_not_fraud_sampled,df_fraud],axis=0).sample(frac=1,replace=False,random_state=101).reset_index().drop('index',axis=1)
df_balance

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,160613.0,1.909865,-0.491574,-0.813714,0.473652,-0.387551,0.204039,-0.929339,0.299490,1.292635,...,-0.053548,-0.169027,0.142538,-1.172274,-0.493808,0.213010,0.001761,-0.023720,45.87,0
1,85285.0,-6.713407,3.921104,-9.746678,5.148263,-5.151563,-2.099389,-5.937767,3.578780,-4.684952,...,0.954272,-0.451086,0.127214,-0.339450,0.394096,1.075295,1.649906,-0.394905,252.92,1
2,35363.0,0.787830,-0.605036,0.821359,0.970535,-1.009319,-0.374111,-0.045690,-0.003127,0.550824,...,-0.201973,-0.807227,0.086205,0.622867,-0.020591,0.168956,-0.032407,0.053456,187.00,0
3,157522.0,1.294819,-1.941765,-3.008082,-0.196133,-0.106729,-1.073717,1.107642,-0.635734,-1.437636,...,0.223172,0.163542,-0.561044,-0.299202,0.321753,0.974463,-0.214628,-0.022205,491.58,0
4,155965.0,-1.201398,4.864535,-8.328823,7.652399,-0.167445,-2.767695,-3.176421,1.623279,-4.367228,...,0.532320,-0.556913,0.192444,-0.698588,0.025003,0.514968,0.378105,-0.053133,0.77,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,37167.0,-7.923891,-5.198360,-3.000024,4.420666,2.272194,-3.394483,-5.283435,0.131619,0.658176,...,-0.734308,-0.599926,-4.908301,0.410170,-1.167660,0.520508,1.937421,-1.552593,12.31,1
942,132688.0,0.432554,1.861373,-4.310353,2.448080,4.574094,-2.979912,-2.792379,-2.719867,-0.276704,...,-1.384477,-0.348904,-3.979948,-0.828156,-2.419446,-0.767070,0.387039,0.319402,1.00,1
943,64493.0,1.135544,0.051081,0.088223,0.912315,-0.052680,-0.020250,-0.063525,0.171887,0.017372,...,0.078057,0.130418,-0.120682,-0.344947,0.557820,-0.292109,0.009606,0.003508,27.39,0
944,20332.0,-15.271362,8.326581,-22.338591,11.885313,-8.721334,-2.324307,-16.196419,0.512882,-6.333685,...,-2.356896,1.068019,1.085617,-1.039797,-0.182006,0.649921,2.149247,-1.406811,1.00,1
945,142409.0,-1.172183,1.661713,-3.049637,2.555058,3.669035,-3.162998,-5.985640,-2.179935,-1.120292,...,-0.812098,-0.295361,-5.988806,0.714381,-1.600024,-0.634783,0.822713,0.494375,2.00,1

In [100]:
fraud_count= df_balance["Class"].value_counts()
fraud_rate = 100*fraud_count/df_balance.shape[0]
fraud_data = pd.concat([fraud_count,fraud_rate], axis=1).reset_index()
fraud_data.columns = ['Class', 'Count','Percentage']
fraud_data

   Class  Count  Percentage
0      0    473        50.0
1      1    473        50.0

In [101]:
X_train, X_test, y_train,y_test = train_test_split(df_balance.drop('Class', axis=1), df_balance['Class'], test_size=0.2, random_state=101)
X_train.shape,y_train.shape

((756, 30), (756,))

fit a random forest model

In [102]:
randomForestModel =Pipeline([ ('scaler', StandardScaler ()),('classifier', RandomForestClassifier ())
                            ])
randomForestModel.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier', RandomForestClassifier())])

In [103]:
y_pred_logis = randomForestModel.predict(X_test)
y_pred_logis

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0])

In [84]:
cr =classification_report(y_test, y_pred_logis)
print(cr)

              precision    recall  f1-score   support

           0       0.95      0.99      0.97       105
           1       0.99      0.94      0.96        85

    accuracy                           0.97       190
   macro avg       0.97      0.97      0.97       190
weighted avg       0.97      0.97      0.97       190